http:
  ip: 0.0.0.0
  port: 3000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h 
  verificationCodeLength: 8

postgres:
  databaseName: chat_db